volumes:
  minio:

services:
   minio:
    image: quay.io/minio/minio:RELEASE.2024-08-17T01-24-54Z
    platform: "linux/amd64"
    command: server /data --console-address :9001
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default
      - internal_net